name: turnkey_oss
description: Public monorepo for Turnkey SDK & API
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/api-key-stamper
  - packages/crypto
  - packages/encoding
  - packages/http
  - packages/passkey-stamper
  - packages/sdk-flutter
  - packages/sessions

dev_dependencies:
  melos: 7.1.1
