name: turnkey_encoding
description: |
  This package provides encoding and decoding functions used by other Turnkey packages. 
  Feel free to import the exported functions into your own apps, 
  but be aware that significant interface changes may occur in the future.
version: 0.1.0
repository: https://github.com/tkhq/dart-sdk

environment:
  sdk: ^3.6.1

resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
