import 'dart:io';
import 'package:path/path.dart' as path;

final String INPUT_SWAGGER_DIRECTORY = Directory('lib/swagger').absolute.path;
final String OUTPUT_GENERATED_DIRECTORY =  Directory('lib/__generated__/services/coordinator/v1').absolute.path;

final GENERATED_DIR = path.join(Directory.current.path, '../__generated__/');

const STAMP_HEADER_FIELD_KEY = "X-Stamp-WebAuthn";
const COMMENT_HEADER =
    "/* @generated by `turnkey_codegen`. DO NOT EDIT BY HAND */";

