/* @generated by `@turnkey/fetchers`. DO NOT EDIT BY HAND */

import '../../../../base.dart';
import 'public_api.swagger.dart';

/// `POST /public/v1/query/get_activity`
typedef TGetActivityResponse = V1ActivityResponse;

/// `POST /public/v1/query/get_activity`
class TGetActivityInput {
  final TGetActivityBody body;

  TGetActivityInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_activity`
typedef TGetActivityBody = V1GetActivityRequest;

/// `POST /public/v1/query/get_api_key`
typedef TGetApiKeyResponse = V1GetApiKeyResponse;

/// `POST /public/v1/query/get_api_key`
class TGetApiKeyInput {
  final TGetApiKeyBody body;

  TGetApiKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_api_key`
typedef TGetApiKeyBody = V1GetApiKeyRequest;

/// `POST /public/v1/query/get_api_keys`
typedef TGetApiKeysResponse = V1GetApiKeysResponse;

/// `POST /public/v1/query/get_api_keys`
class TGetApiKeysInput {
  final TGetApiKeysBody body;

  TGetApiKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_api_keys`
typedef TGetApiKeysBody = V1GetApiKeysRequest;

/// `POST /public/v1/query/get_attestation`
typedef TGetAttestationDocumentResponse = V1GetAttestationDocumentResponse;

/// `POST /public/v1/query/get_attestation`
class TGetAttestationDocumentInput {
  final TGetAttestationDocumentBody body;

  TGetAttestationDocumentInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_attestation`
typedef TGetAttestationDocumentBody = V1GetAttestationDocumentRequest;

/// `POST /public/v1/query/get_authenticator`
typedef TGetAuthenticatorResponse = V1GetAuthenticatorResponse;

/// `POST /public/v1/query/get_authenticator`
class TGetAuthenticatorInput {
  final TGetAuthenticatorBody body;

  TGetAuthenticatorInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_authenticator`
typedef TGetAuthenticatorBody = V1GetAuthenticatorRequest;

/// `POST /public/v1/query/get_authenticators`
typedef TGetAuthenticatorsResponse = V1GetAuthenticatorsResponse;

/// `POST /public/v1/query/get_authenticators`
class TGetAuthenticatorsInput {
  final TGetAuthenticatorsBody body;

  TGetAuthenticatorsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_authenticators`
typedef TGetAuthenticatorsBody = V1GetAuthenticatorsRequest;

/// `POST /public/v1/query/get_oauth_providers`
typedef TGetOauthProvidersResponse = V1GetOauthProvidersResponse;

/// `POST /public/v1/query/get_oauth_providers`
class TGetOauthProvidersInput {
  final TGetOauthProvidersBody body;

  TGetOauthProvidersInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_oauth_providers`
typedef TGetOauthProvidersBody = V1GetOauthProvidersRequest;

/// `POST /public/v1/query/get_organization`
typedef TGetOrganizationResponse = V1GetOrganizationResponse;

/// `POST /public/v1/query/get_organization`
class TGetOrganizationInput {
  final TGetOrganizationBody body;

  TGetOrganizationInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_organization`
typedef TGetOrganizationBody = V1GetOrganizationRequest;

/// `POST /public/v1/query/get_organization_configs`
typedef TGetOrganizationConfigsResponse = V1GetOrganizationConfigsResponse;

/// `POST /public/v1/query/get_organization_configs`
class TGetOrganizationConfigsInput {
  final TGetOrganizationConfigsBody body;

  TGetOrganizationConfigsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_organization_configs`
typedef TGetOrganizationConfigsBody = V1GetOrganizationConfigsRequest;

/// `POST /public/v1/query/get_policy`
typedef TGetPolicyResponse = V1GetPolicyResponse;

/// `POST /public/v1/query/get_policy`
class TGetPolicyInput {
  final TGetPolicyBody body;

  TGetPolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_policy`
typedef TGetPolicyBody = V1GetPolicyRequest;

/// `POST /public/v1/query/get_private_key`
typedef TGetPrivateKeyResponse = V1GetPrivateKeyResponse;

/// `POST /public/v1/query/get_private_key`
class TGetPrivateKeyInput {
  final TGetPrivateKeyBody body;

  TGetPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_private_key`
typedef TGetPrivateKeyBody = V1GetPrivateKeyRequest;

/// `POST /public/v1/query/get_user`
typedef TGetUserResponse = V1GetUserResponse;

/// `POST /public/v1/query/get_user`
class TGetUserInput {
  final TGetUserBody body;

  TGetUserInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_user`
typedef TGetUserBody = V1GetUserRequest;

/// `POST /public/v1/query/get_wallet`
typedef TGetWalletResponse = V1GetWalletResponse;

/// `POST /public/v1/query/get_wallet`
class TGetWalletInput {
  final TGetWalletBody body;

  TGetWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_wallet`
typedef TGetWalletBody = V1GetWalletRequest;

/// `POST /public/v1/query/list_activities`
typedef TGetActivitiesResponse = V1GetActivitiesResponse;

/// `POST /public/v1/query/list_activities`
class TGetActivitiesInput {
  final TGetActivitiesBody body;

  TGetActivitiesInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_activities`
typedef TGetActivitiesBody = V1GetActivitiesRequest;

/// `POST /public/v1/query/list_policies`
typedef TGetPoliciesResponse = V1GetPoliciesResponse;

/// `POST /public/v1/query/list_policies`
class TGetPoliciesInput {
  final TGetPoliciesBody body;

  TGetPoliciesInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_policies`
typedef TGetPoliciesBody = V1GetPoliciesRequest;

/// `POST /public/v1/query/list_private_key_tags`
typedef TListPrivateKeyTagsResponse = V1ListPrivateKeyTagsResponse;

/// `POST /public/v1/query/list_private_key_tags`
class TListPrivateKeyTagsInput {
  final TListPrivateKeyTagsBody body;

  TListPrivateKeyTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_private_key_tags`
typedef TListPrivateKeyTagsBody = V1ListPrivateKeyTagsRequest;

/// `POST /public/v1/query/list_private_keys`
typedef TGetPrivateKeysResponse = V1GetPrivateKeysResponse;

/// `POST /public/v1/query/list_private_keys`
class TGetPrivateKeysInput {
  final TGetPrivateKeysBody body;

  TGetPrivateKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_private_keys`
typedef TGetPrivateKeysBody = V1GetPrivateKeysRequest;

/// `POST /public/v1/query/list_suborgs`
typedef TGetSubOrgIdsResponse = V1GetSubOrgIdsResponse;

/// `POST /public/v1/query/list_suborgs`
class TGetSubOrgIdsInput {
  final TGetSubOrgIdsBody body;

  TGetSubOrgIdsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_suborgs`
typedef TGetSubOrgIdsBody = V1GetSubOrgIdsRequest;

/// `POST /public/v1/query/list_user_tags`
typedef TListUserTagsResponse = V1ListUserTagsResponse;

/// `POST /public/v1/query/list_user_tags`
class TListUserTagsInput {
  final TListUserTagsBody body;

  TListUserTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_user_tags`
typedef TListUserTagsBody = V1ListUserTagsRequest;

/// `POST /public/v1/query/list_users`
typedef TGetUsersResponse = V1GetUsersResponse;

/// `POST /public/v1/query/list_users`
class TGetUsersInput {
  final TGetUsersBody body;

  TGetUsersInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_users`
typedef TGetUsersBody = V1GetUsersRequest;

/// `POST /public/v1/query/list_verified_suborgs`
typedef TGetVerifiedSubOrgIdsResponse = V1GetVerifiedSubOrgIdsResponse;

/// `POST /public/v1/query/list_verified_suborgs`
class TGetVerifiedSubOrgIdsInput {
  final TGetVerifiedSubOrgIdsBody body;

  TGetVerifiedSubOrgIdsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_verified_suborgs`
typedef TGetVerifiedSubOrgIdsBody = V1GetVerifiedSubOrgIdsRequest;

/// `POST /public/v1/query/list_wallet_accounts`
typedef TGetWalletAccountsResponse = V1GetWalletAccountsResponse;

/// `POST /public/v1/query/list_wallet_accounts`
class TGetWalletAccountsInput {
  final TGetWalletAccountsBody body;

  TGetWalletAccountsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_wallet_accounts`
typedef TGetWalletAccountsBody = V1GetWalletAccountsRequest;

/// `POST /public/v1/query/list_wallets`
typedef TGetWalletsResponse = V1GetWalletsResponse;

/// `POST /public/v1/query/list_wallets`
class TGetWalletsInput {
  final TGetWalletsBody body;

  TGetWalletsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_wallets`
typedef TGetWalletsBody = V1GetWalletsRequest;

/// `POST /public/v1/query/whoami`
typedef TGetWhoamiResponse = V1GetWhoamiResponse;

/// `POST /public/v1/query/whoami`
class TGetWhoamiInput {
  final TGetWhoamiBody body;

  TGetWhoamiInput({
    required this.body,
  });
}

/// `POST /public/v1/query/whoami`
typedef TGetWhoamiBody = V1GetWhoamiRequest;

/// `POST /public/v1/submit/approve_activity`
typedef TApproveActivityResponse = V1ActivityResponse;

/// `POST /public/v1/submit/approve_activity`
class TApproveActivityInput {
  final TApproveActivityBody body;

  TApproveActivityInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/approve_activity`
typedef TApproveActivityBody = V1ApproveActivityRequest;

/// `POST /public/v1/submit/create_api_keys`
typedef TCreateApiKeysResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_api_keys`
class TCreateApiKeysInput {
  final TCreateApiKeysBody body;

  TCreateApiKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_api_keys`
typedef TCreateApiKeysBody = V1CreateApiKeysRequest;

/// `POST /public/v1/submit/create_api_only_users`
typedef TCreateApiOnlyUsersResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_api_only_users`
class TCreateApiOnlyUsersInput {
  final TCreateApiOnlyUsersBody body;

  TCreateApiOnlyUsersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_api_only_users`
typedef TCreateApiOnlyUsersBody = V1CreateApiOnlyUsersRequest;

/// `POST /public/v1/submit/create_authenticators`
typedef TCreateAuthenticatorsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_authenticators`
class TCreateAuthenticatorsInput {
  final TCreateAuthenticatorsBody body;

  TCreateAuthenticatorsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_authenticators`
typedef TCreateAuthenticatorsBody = V1CreateAuthenticatorsRequest;

/// `POST /public/v1/submit/create_invitations`
typedef TCreateInvitationsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_invitations`
class TCreateInvitationsInput {
  final TCreateInvitationsBody body;

  TCreateInvitationsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_invitations`
typedef TCreateInvitationsBody = V1CreateInvitationsRequest;

/// `POST /public/v1/submit/create_oauth_providers`
typedef TCreateOauthProvidersResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_oauth_providers`
class TCreateOauthProvidersInput {
  final TCreateOauthProvidersBody body;

  TCreateOauthProvidersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_oauth_providers`
typedef TCreateOauthProvidersBody = V1CreateOauthProvidersRequest;

/// `POST /public/v1/submit/create_policies`
typedef TCreatePoliciesResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_policies`
class TCreatePoliciesInput {
  final TCreatePoliciesBody body;

  TCreatePoliciesInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_policies`
typedef TCreatePoliciesBody = V1CreatePoliciesRequest;

/// `POST /public/v1/submit/create_policy`
typedef TCreatePolicyResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_policy`
class TCreatePolicyInput {
  final TCreatePolicyBody body;

  TCreatePolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_policy`
typedef TCreatePolicyBody = V1CreatePolicyRequest;

/// `POST /public/v1/submit/create_private_key_tag`
typedef TCreatePrivateKeyTagResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_private_key_tag`
class TCreatePrivateKeyTagInput {
  final TCreatePrivateKeyTagBody body;

  TCreatePrivateKeyTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_private_key_tag`
typedef TCreatePrivateKeyTagBody = V1CreatePrivateKeyTagRequest;

/// `POST /public/v1/submit/create_private_keys`
typedef TCreatePrivateKeysResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_private_keys`
class TCreatePrivateKeysInput {
  final TCreatePrivateKeysBody body;

  TCreatePrivateKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_private_keys`
typedef TCreatePrivateKeysBody = V1CreatePrivateKeysRequest;

/// `POST /public/v1/submit/create_read_only_session`
typedef TCreateReadOnlySessionResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_read_only_session`
class TCreateReadOnlySessionInput {
  final TCreateReadOnlySessionBody body;

  TCreateReadOnlySessionInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_read_only_session`
typedef TCreateReadOnlySessionBody = V1CreateReadOnlySessionRequest;

/// `POST /public/v1/submit/create_read_write_session`
typedef TCreateReadWriteSessionResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_read_write_session`
class TCreateReadWriteSessionInput {
  final TCreateReadWriteSessionBody body;

  TCreateReadWriteSessionInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_read_write_session`
typedef TCreateReadWriteSessionBody = V1CreateReadWriteSessionRequest;

/// `POST /public/v1/submit/create_sub_organization`
typedef TCreateSubOrganizationResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_sub_organization`
class TCreateSubOrganizationInput {
  final TCreateSubOrganizationBody body;

  TCreateSubOrganizationInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_sub_organization`
typedef TCreateSubOrganizationBody = V1CreateSubOrganizationRequest;

/// `POST /public/v1/submit/create_user_tag`
typedef TCreateUserTagResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_user_tag`
class TCreateUserTagInput {
  final TCreateUserTagBody body;

  TCreateUserTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_user_tag`
typedef TCreateUserTagBody = V1CreateUserTagRequest;

/// `POST /public/v1/submit/create_users`
typedef TCreateUsersResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_users`
class TCreateUsersInput {
  final TCreateUsersBody body;

  TCreateUsersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_users`
typedef TCreateUsersBody = V1CreateUsersRequest;

/// `POST /public/v1/submit/create_wallet`
typedef TCreateWalletResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_wallet`
class TCreateWalletInput {
  final TCreateWalletBody body;

  TCreateWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_wallet`
typedef TCreateWalletBody = V1CreateWalletRequest;

/// `POST /public/v1/submit/create_wallet_accounts`
typedef TCreateWalletAccountsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/create_wallet_accounts`
class TCreateWalletAccountsInput {
  final TCreateWalletAccountsBody body;

  TCreateWalletAccountsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_wallet_accounts`
typedef TCreateWalletAccountsBody = V1CreateWalletAccountsRequest;

/// `POST /public/v1/submit/delete_api_keys`
typedef TDeleteApiKeysResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_api_keys`
class TDeleteApiKeysInput {
  final TDeleteApiKeysBody body;

  TDeleteApiKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_api_keys`
typedef TDeleteApiKeysBody = V1DeleteApiKeysRequest;

/// `POST /public/v1/submit/delete_authenticators`
typedef TDeleteAuthenticatorsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_authenticators`
class TDeleteAuthenticatorsInput {
  final TDeleteAuthenticatorsBody body;

  TDeleteAuthenticatorsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_authenticators`
typedef TDeleteAuthenticatorsBody = V1DeleteAuthenticatorsRequest;

/// `POST /public/v1/submit/delete_invitation`
typedef TDeleteInvitationResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_invitation`
class TDeleteInvitationInput {
  final TDeleteInvitationBody body;

  TDeleteInvitationInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_invitation`
typedef TDeleteInvitationBody = V1DeleteInvitationRequest;

/// `POST /public/v1/submit/delete_oauth_providers`
typedef TDeleteOauthProvidersResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_oauth_providers`
class TDeleteOauthProvidersInput {
  final TDeleteOauthProvidersBody body;

  TDeleteOauthProvidersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_oauth_providers`
typedef TDeleteOauthProvidersBody = V1DeleteOauthProvidersRequest;

/// `POST /public/v1/submit/delete_policy`
typedef TDeletePolicyResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_policy`
class TDeletePolicyInput {
  final TDeletePolicyBody body;

  TDeletePolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_policy`
typedef TDeletePolicyBody = V1DeletePolicyRequest;

/// `POST /public/v1/submit/delete_private_key_tags`
typedef TDeletePrivateKeyTagsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_private_key_tags`
class TDeletePrivateKeyTagsInput {
  final TDeletePrivateKeyTagsBody body;

  TDeletePrivateKeyTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_private_key_tags`
typedef TDeletePrivateKeyTagsBody = V1DeletePrivateKeyTagsRequest;

/// `POST /public/v1/submit/delete_private_keys`
typedef TDeletePrivateKeysResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_private_keys`
class TDeletePrivateKeysInput {
  final TDeletePrivateKeysBody body;

  TDeletePrivateKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_private_keys`
typedef TDeletePrivateKeysBody = V1DeletePrivateKeysRequest;

/// `POST /public/v1/submit/delete_sub_organization`
typedef TDeleteSubOrganizationResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_sub_organization`
class TDeleteSubOrganizationInput {
  final TDeleteSubOrganizationBody body;

  TDeleteSubOrganizationInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_sub_organization`
typedef TDeleteSubOrganizationBody = V1DeleteSubOrganizationRequest;

/// `POST /public/v1/submit/delete_user_tags`
typedef TDeleteUserTagsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_user_tags`
class TDeleteUserTagsInput {
  final TDeleteUserTagsBody body;

  TDeleteUserTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_user_tags`
typedef TDeleteUserTagsBody = V1DeleteUserTagsRequest;

/// `POST /public/v1/submit/delete_users`
typedef TDeleteUsersResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_users`
class TDeleteUsersInput {
  final TDeleteUsersBody body;

  TDeleteUsersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_users`
typedef TDeleteUsersBody = V1DeleteUsersRequest;

/// `POST /public/v1/submit/delete_wallets`
typedef TDeleteWalletsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/delete_wallets`
class TDeleteWalletsInput {
  final TDeleteWalletsBody body;

  TDeleteWalletsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_wallets`
typedef TDeleteWalletsBody = V1DeleteWalletsRequest;

/// `POST /public/v1/submit/email_auth`
typedef TEmailAuthResponse = V1ActivityResponse;

/// `POST /public/v1/submit/email_auth`
class TEmailAuthInput {
  final TEmailAuthBody body;

  TEmailAuthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/email_auth`
typedef TEmailAuthBody = V1EmailAuthRequest;

/// `POST /public/v1/submit/export_private_key`
typedef TExportPrivateKeyResponse = V1ActivityResponse;

/// `POST /public/v1/submit/export_private_key`
class TExportPrivateKeyInput {
  final TExportPrivateKeyBody body;

  TExportPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/export_private_key`
typedef TExportPrivateKeyBody = V1ExportPrivateKeyRequest;

/// `POST /public/v1/submit/export_wallet`
typedef TExportWalletResponse = V1ActivityResponse;

/// `POST /public/v1/submit/export_wallet`
class TExportWalletInput {
  final TExportWalletBody body;

  TExportWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/export_wallet`
typedef TExportWalletBody = V1ExportWalletRequest;

/// `POST /public/v1/submit/export_wallet_account`
typedef TExportWalletAccountResponse = V1ActivityResponse;

/// `POST /public/v1/submit/export_wallet_account`
class TExportWalletAccountInput {
  final TExportWalletAccountBody body;

  TExportWalletAccountInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/export_wallet_account`
typedef TExportWalletAccountBody = V1ExportWalletAccountRequest;

/// `POST /public/v1/submit/import_private_key`
typedef TImportPrivateKeyResponse = V1ActivityResponse;

/// `POST /public/v1/submit/import_private_key`
class TImportPrivateKeyInput {
  final TImportPrivateKeyBody body;

  TImportPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/import_private_key`
typedef TImportPrivateKeyBody = V1ImportPrivateKeyRequest;

/// `POST /public/v1/submit/import_wallet`
typedef TImportWalletResponse = V1ActivityResponse;

/// `POST /public/v1/submit/import_wallet`
class TImportWalletInput {
  final TImportWalletBody body;

  TImportWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/import_wallet`
typedef TImportWalletBody = V1ImportWalletRequest;

/// `POST /public/v1/submit/init_import_private_key`
typedef TInitImportPrivateKeyResponse = V1ActivityResponse;

/// `POST /public/v1/submit/init_import_private_key`
class TInitImportPrivateKeyInput {
  final TInitImportPrivateKeyBody body;

  TInitImportPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_import_private_key`
typedef TInitImportPrivateKeyBody = V1InitImportPrivateKeyRequest;

/// `POST /public/v1/submit/init_import_wallet`
typedef TInitImportWalletResponse = V1ActivityResponse;

/// `POST /public/v1/submit/init_import_wallet`
class TInitImportWalletInput {
  final TInitImportWalletBody body;

  TInitImportWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_import_wallet`
typedef TInitImportWalletBody = V1InitImportWalletRequest;

/// `POST /public/v1/submit/init_otp_auth`
typedef TInitOtpAuthResponse = V1ActivityResponse;

/// `POST /public/v1/submit/init_otp_auth`
class TInitOtpAuthInput {
  final TInitOtpAuthBody body;

  TInitOtpAuthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_otp_auth`
typedef TInitOtpAuthBody = V1InitOtpAuthRequest;

/// `POST /public/v1/submit/init_user_email_recovery`
typedef TInitUserEmailRecoveryResponse = V1ActivityResponse;

/// `POST /public/v1/submit/init_user_email_recovery`
class TInitUserEmailRecoveryInput {
  final TInitUserEmailRecoveryBody body;

  TInitUserEmailRecoveryInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_user_email_recovery`
typedef TInitUserEmailRecoveryBody = V1InitUserEmailRecoveryRequest;

/// `POST /public/v1/submit/oauth`
typedef TOauthResponse = V1ActivityResponse;

/// `POST /public/v1/submit/oauth`
class TOauthInput {
  final TOauthBody body;

  TOauthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/oauth`
typedef TOauthBody = V1OauthRequest;

/// `POST /public/v1/submit/otp_auth`
typedef TOtpAuthResponse = V1ActivityResponse;

/// `POST /public/v1/submit/otp_auth`
class TOtpAuthInput {
  final TOtpAuthBody body;

  TOtpAuthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/otp_auth`
typedef TOtpAuthBody = V1OtpAuthRequest;

/// `POST /public/v1/submit/recover_user`
typedef TRecoverUserResponse = V1ActivityResponse;

/// `POST /public/v1/submit/recover_user`
class TRecoverUserInput {
  final TRecoverUserBody body;

  TRecoverUserInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/recover_user`
typedef TRecoverUserBody = V1RecoverUserRequest;

/// `POST /public/v1/submit/reject_activity`
typedef TRejectActivityResponse = V1ActivityResponse;

/// `POST /public/v1/submit/reject_activity`
class TRejectActivityInput {
  final TRejectActivityBody body;

  TRejectActivityInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/reject_activity`
typedef TRejectActivityBody = V1RejectActivityRequest;

/// `POST /public/v1/submit/remove_organization_feature`
typedef TRemoveOrganizationFeatureResponse = V1ActivityResponse;

/// `POST /public/v1/submit/remove_organization_feature`
class TRemoveOrganizationFeatureInput {
  final TRemoveOrganizationFeatureBody body;

  TRemoveOrganizationFeatureInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/remove_organization_feature`
typedef TRemoveOrganizationFeatureBody = V1RemoveOrganizationFeatureRequest;

/// `POST /public/v1/submit/set_organization_feature`
typedef TSetOrganizationFeatureResponse = V1ActivityResponse;

/// `POST /public/v1/submit/set_organization_feature`
class TSetOrganizationFeatureInput {
  final TSetOrganizationFeatureBody body;

  TSetOrganizationFeatureInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/set_organization_feature`
typedef TSetOrganizationFeatureBody = V1SetOrganizationFeatureRequest;

/// `POST /public/v1/submit/sign_raw_payload`
typedef TSignRawPayloadResponse = V1ActivityResponse;

/// `POST /public/v1/submit/sign_raw_payload`
class TSignRawPayloadInput {
  final TSignRawPayloadBody body;

  TSignRawPayloadInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/sign_raw_payload`
typedef TSignRawPayloadBody = V1SignRawPayloadRequest;

/// `POST /public/v1/submit/sign_raw_payloads`
typedef TSignRawPayloadsResponse = V1ActivityResponse;

/// `POST /public/v1/submit/sign_raw_payloads`
class TSignRawPayloadsInput {
  final TSignRawPayloadsBody body;

  TSignRawPayloadsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/sign_raw_payloads`
typedef TSignRawPayloadsBody = V1SignRawPayloadsRequest;

/// `POST /public/v1/submit/sign_transaction`
typedef TSignTransactionResponse = V1ActivityResponse;

/// `POST /public/v1/submit/sign_transaction`
class TSignTransactionInput {
  final TSignTransactionBody body;

  TSignTransactionInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/sign_transaction`
typedef TSignTransactionBody = V1SignTransactionRequest;

/// `POST /public/v1/submit/update_policy`
typedef TUpdatePolicyResponse = V1ActivityResponse;

/// `POST /public/v1/submit/update_policy`
class TUpdatePolicyInput {
  final TUpdatePolicyBody body;

  TUpdatePolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_policy`
typedef TUpdatePolicyBody = V1UpdatePolicyRequest;

/// `POST /public/v1/submit/update_private_key_tag`
typedef TUpdatePrivateKeyTagResponse = V1ActivityResponse;

/// `POST /public/v1/submit/update_private_key_tag`
class TUpdatePrivateKeyTagInput {
  final TUpdatePrivateKeyTagBody body;

  TUpdatePrivateKeyTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_private_key_tag`
typedef TUpdatePrivateKeyTagBody = V1UpdatePrivateKeyTagRequest;

/// `POST /public/v1/submit/update_root_quorum`
typedef TUpdateRootQuorumResponse = V1ActivityResponse;

/// `POST /public/v1/submit/update_root_quorum`
class TUpdateRootQuorumInput {
  final TUpdateRootQuorumBody body;

  TUpdateRootQuorumInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_root_quorum`
typedef TUpdateRootQuorumBody = V1UpdateRootQuorumRequest;

/// `POST /public/v1/submit/update_user`
typedef TUpdateUserResponse = V1ActivityResponse;

/// `POST /public/v1/submit/update_user`
class TUpdateUserInput {
  final TUpdateUserBody body;

  TUpdateUserInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_user`
typedef TUpdateUserBody = V1UpdateUserRequest;

/// `POST /public/v1/submit/update_user_tag`
typedef TUpdateUserTagResponse = V1ActivityResponse;

/// `POST /public/v1/submit/update_user_tag`
class TUpdateUserTagInput {
  final TUpdateUserTagBody body;

  TUpdateUserTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_user_tag`
typedef TUpdateUserTagBody = V1UpdateUserTagRequest;

/// `POST /tkhq/api/v1/noop-codegen-anchor`
typedef TNOOPCodegenAnchorResponse = V1NOOPCodegenAnchorResponse;
