name: turnkey_flutter_demo_app
description: "A demo app using Turnkey's Flutter packages"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
repository: https://github.com/tkhq/dart-sdk

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pinput: ^5.0.1
  flutter_svg: ^1.0.3
  http: ^1.3.0
  #TODO: These should be replaced with the published package
  turnkey_crypto:
    path: ../../crypto
  turnkey_flutter_passkey_stamper:
    path: ../../passkey-stamper
  turnkey_api_stamper:
    path: ../../api-stamper
  turnkey_http_client:
    path: ../../http
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  elliptic: ^0.3.11
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.6
  openid_client: ^0.4.9
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - .env
