/* @generated by `turnkey_codegen`. DO NOT EDIT BY HAND */

import 'public_api.swagger.dart';

/// `POST /public/v1/query/get_activity`
typedef TGetActivityResponse = ActivityResponse;

/// `POST /public/v1/query/get_activity`
class TGetActivityInput {
  final TGetActivityBody body;

  TGetActivityInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_activity`
typedef TGetActivityBody = GetActivityRequest;

/// `POST /public/v1/query/get_api_key`
typedef TGetApiKeyResponse = GetApiKeyResponse;

/// `POST /public/v1/query/get_api_key`
class TGetApiKeyInput {
  final TGetApiKeyBody body;

  TGetApiKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_api_key`
typedef TGetApiKeyBody = GetApiKeyRequest;

/// `POST /public/v1/query/get_api_keys`
typedef TGetApiKeysResponse = GetApiKeysResponse;

/// `POST /public/v1/query/get_api_keys`
class TGetApiKeysInput {
  final TGetApiKeysBody body;

  TGetApiKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_api_keys`
typedef TGetApiKeysBody = GetApiKeysRequest;

/// `POST /public/v1/query/get_authenticator`
typedef TGetAuthenticatorResponse = GetAuthenticatorResponse;

/// `POST /public/v1/query/get_authenticator`
class TGetAuthenticatorInput {
  final TGetAuthenticatorBody body;

  TGetAuthenticatorInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_authenticator`
typedef TGetAuthenticatorBody = GetAuthenticatorRequest;

/// `POST /public/v1/query/get_authenticators`
typedef TGetAuthenticatorsResponse = GetAuthenticatorsResponse;

/// `POST /public/v1/query/get_authenticators`
class TGetAuthenticatorsInput {
  final TGetAuthenticatorsBody body;

  TGetAuthenticatorsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_authenticators`
typedef TGetAuthenticatorsBody = GetAuthenticatorsRequest;

/// `POST /public/v1/query/get_oauth_providers`
typedef TGetOauthProvidersResponse = GetOauthProvidersResponse;

/// `POST /public/v1/query/get_oauth_providers`
class TGetOauthProvidersInput {
  final TGetOauthProvidersBody body;

  TGetOauthProvidersInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_oauth_providers`
typedef TGetOauthProvidersBody = GetOauthProvidersRequest;

/// `POST /public/v1/query/get_organization_configs`
typedef TGetOrganizationConfigsResponse = GetOrganizationConfigsResponse;

/// `POST /public/v1/query/get_organization_configs`
class TGetOrganizationConfigsInput {
  final TGetOrganizationConfigsBody body;

  TGetOrganizationConfigsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_organization_configs`
typedef TGetOrganizationConfigsBody = GetOrganizationConfigsRequest;

/// `POST /public/v1/query/get_policy`
typedef TGetPolicyResponse = GetPolicyResponse;

/// `POST /public/v1/query/get_policy`
class TGetPolicyInput {
  final TGetPolicyBody body;

  TGetPolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_policy`
typedef TGetPolicyBody = GetPolicyRequest;

/// `POST /public/v1/query/get_policy_evaluations`
typedef TGetPolicyEvaluationsResponse = GetPolicyEvaluationsResponse;

/// `POST /public/v1/query/get_policy_evaluations`
class TGetPolicyEvaluationsInput {
  final TGetPolicyEvaluationsBody body;

  TGetPolicyEvaluationsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_policy_evaluations`
typedef TGetPolicyEvaluationsBody = GetPolicyEvaluationsRequest;

/// `POST /public/v1/query/get_private_key`
typedef TGetPrivateKeyResponse = GetPrivateKeyResponse;

/// `POST /public/v1/query/get_private_key`
class TGetPrivateKeyInput {
  final TGetPrivateKeyBody body;

  TGetPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_private_key`
typedef TGetPrivateKeyBody = GetPrivateKeyRequest;

/// `POST /public/v1/query/get_smart_contract_interface`
typedef TGetSmartContractInterfaceResponse = GetSmartContractInterfaceResponse;

/// `POST /public/v1/query/get_smart_contract_interface`
class TGetSmartContractInterfaceInput {
  final TGetSmartContractInterfaceBody body;

  TGetSmartContractInterfaceInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_smart_contract_interface`
typedef TGetSmartContractInterfaceBody = GetSmartContractInterfaceRequest;

/// `POST /public/v1/query/get_user`
typedef TGetUserResponse = GetUserResponse;

/// `POST /public/v1/query/get_user`
class TGetUserInput {
  final TGetUserBody body;

  TGetUserInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_user`
typedef TGetUserBody = GetUserRequest;

/// `POST /public/v1/query/get_wallet`
typedef TGetWalletResponse = GetWalletResponse;

/// `POST /public/v1/query/get_wallet`
class TGetWalletInput {
  final TGetWalletBody body;

  TGetWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_wallet`
typedef TGetWalletBody = GetWalletRequest;

/// `POST /public/v1/query/get_wallet_account`
typedef TGetWalletAccountResponse = GetWalletAccountResponse;

/// `POST /public/v1/query/get_wallet_account`
class TGetWalletAccountInput {
  final TGetWalletAccountBody body;

  TGetWalletAccountInput({
    required this.body,
  });
}

/// `POST /public/v1/query/get_wallet_account`
typedef TGetWalletAccountBody = GetWalletAccountRequest;

/// `POST /public/v1/query/list_activities`
typedef TGetActivitiesResponse = GetActivitiesResponse;

/// `POST /public/v1/query/list_activities`
class TGetActivitiesInput {
  final TGetActivitiesBody body;

  TGetActivitiesInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_activities`
typedef TGetActivitiesBody = GetActivitiesRequest;

/// `POST /public/v1/query/list_policies`
typedef TGetPoliciesResponse = GetPoliciesResponse;

/// `POST /public/v1/query/list_policies`
class TGetPoliciesInput {
  final TGetPoliciesBody body;

  TGetPoliciesInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_policies`
typedef TGetPoliciesBody = GetPoliciesRequest;

/// `POST /public/v1/query/list_private_key_tags`
typedef TListPrivateKeyTagsResponse = ListPrivateKeyTagsResponse;

/// `POST /public/v1/query/list_private_key_tags`
class TListPrivateKeyTagsInput {
  final TListPrivateKeyTagsBody body;

  TListPrivateKeyTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_private_key_tags`
typedef TListPrivateKeyTagsBody = ListPrivateKeyTagsRequest;

/// `POST /public/v1/query/list_private_keys`
typedef TGetPrivateKeysResponse = GetPrivateKeysResponse;

/// `POST /public/v1/query/list_private_keys`
class TGetPrivateKeysInput {
  final TGetPrivateKeysBody body;

  TGetPrivateKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_private_keys`
typedef TGetPrivateKeysBody = GetPrivateKeysRequest;

/// `POST /public/v1/query/list_smart_contract_interfaces`
typedef TGetSmartContractInterfacesResponse
    = GetSmartContractInterfacesResponse;

/// `POST /public/v1/query/list_smart_contract_interfaces`
class TGetSmartContractInterfacesInput {
  final TGetSmartContractInterfacesBody body;

  TGetSmartContractInterfacesInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_smart_contract_interfaces`
typedef TGetSmartContractInterfacesBody = GetSmartContractInterfacesRequest;

/// `POST /public/v1/query/list_suborgs`
typedef TGetSubOrgIdsResponse = GetSubOrgIdsResponse;

/// `POST /public/v1/query/list_suborgs`
class TGetSubOrgIdsInput {
  final TGetSubOrgIdsBody body;

  TGetSubOrgIdsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_suborgs`
typedef TGetSubOrgIdsBody = GetSubOrgIdsRequest;

/// `POST /public/v1/query/list_user_tags`
typedef TListUserTagsResponse = ListUserTagsResponse;

/// `POST /public/v1/query/list_user_tags`
class TListUserTagsInput {
  final TListUserTagsBody body;

  TListUserTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_user_tags`
typedef TListUserTagsBody = ListUserTagsRequest;

/// `POST /public/v1/query/list_users`
typedef TGetUsersResponse = GetUsersResponse;

/// `POST /public/v1/query/list_users`
class TGetUsersInput {
  final TGetUsersBody body;

  TGetUsersInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_users`
typedef TGetUsersBody = GetUsersRequest;

/// `POST /public/v1/query/list_verified_suborgs`
typedef TGetVerifiedSubOrgIdsResponse = GetVerifiedSubOrgIdsResponse;

/// `POST /public/v1/query/list_verified_suborgs`
class TGetVerifiedSubOrgIdsInput {
  final TGetVerifiedSubOrgIdsBody body;

  TGetVerifiedSubOrgIdsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_verified_suborgs`
typedef TGetVerifiedSubOrgIdsBody = GetVerifiedSubOrgIdsRequest;

/// `POST /public/v1/query/list_wallet_accounts`
typedef TGetWalletAccountsResponse = GetWalletAccountsResponse;

/// `POST /public/v1/query/list_wallet_accounts`
class TGetWalletAccountsInput {
  final TGetWalletAccountsBody body;

  TGetWalletAccountsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_wallet_accounts`
typedef TGetWalletAccountsBody = GetWalletAccountsRequest;

/// `POST /public/v1/query/list_wallets`
typedef TGetWalletsResponse = GetWalletsResponse;

/// `POST /public/v1/query/list_wallets`
class TGetWalletsInput {
  final TGetWalletsBody body;

  TGetWalletsInput({
    required this.body,
  });
}

/// `POST /public/v1/query/list_wallets`
typedef TGetWalletsBody = GetWalletsRequest;

/// `POST /public/v1/query/whoami`
typedef TGetWhoamiResponse = GetWhoamiResponse;

/// `POST /public/v1/query/whoami`
class TGetWhoamiInput {
  final TGetWhoamiBody body;

  TGetWhoamiInput({
    required this.body,
  });
}

/// `POST /public/v1/query/whoami`
typedef TGetWhoamiBody = GetWhoamiRequest;

/// `POST /public/v1/submit/approve_activity`
typedef TApproveActivityResponse = ActivityResponse;

/// `POST /public/v1/submit/approve_activity`
class TApproveActivityInput {
  final TApproveActivityBody body;

  TApproveActivityInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/approve_activity`
typedef TApproveActivityBody = ApproveActivityRequest;

/// `POST /public/v1/submit/create_api_keys`
typedef TCreateApiKeysResponse = ActivityResponse;

/// `POST /public/v1/submit/create_api_keys`
class TCreateApiKeysInput {
  final TCreateApiKeysBody body;

  TCreateApiKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_api_keys`
typedef TCreateApiKeysBody = CreateApiKeysRequest;

/// `POST /public/v1/submit/create_authenticators`
typedef TCreateAuthenticatorsResponse = ActivityResponse;

/// `POST /public/v1/submit/create_authenticators`
class TCreateAuthenticatorsInput {
  final TCreateAuthenticatorsBody body;

  TCreateAuthenticatorsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_authenticators`
typedef TCreateAuthenticatorsBody = CreateAuthenticatorsRequest;

/// `POST /public/v1/submit/create_invitations`
typedef TCreateInvitationsResponse = ActivityResponse;

/// `POST /public/v1/submit/create_invitations`
class TCreateInvitationsInput {
  final TCreateInvitationsBody body;

  TCreateInvitationsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_invitations`
typedef TCreateInvitationsBody = CreateInvitationsRequest;

/// `POST /public/v1/submit/create_oauth_providers`
typedef TCreateOauthProvidersResponse = ActivityResponse;

/// `POST /public/v1/submit/create_oauth_providers`
class TCreateOauthProvidersInput {
  final TCreateOauthProvidersBody body;

  TCreateOauthProvidersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_oauth_providers`
typedef TCreateOauthProvidersBody = CreateOauthProvidersRequest;

/// `POST /public/v1/submit/create_policies`
typedef TCreatePoliciesResponse = ActivityResponse;

/// `POST /public/v1/submit/create_policies`
class TCreatePoliciesInput {
  final TCreatePoliciesBody body;

  TCreatePoliciesInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_policies`
typedef TCreatePoliciesBody = CreatePoliciesRequest;

/// `POST /public/v1/submit/create_policy`
typedef TCreatePolicyResponse = ActivityResponse;

/// `POST /public/v1/submit/create_policy`
class TCreatePolicyInput {
  final TCreatePolicyBody body;

  TCreatePolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_policy`
typedef TCreatePolicyBody = CreatePolicyRequest;

/// `POST /public/v1/submit/create_private_key_tag`
typedef TCreatePrivateKeyTagResponse = ActivityResponse;

/// `POST /public/v1/submit/create_private_key_tag`
class TCreatePrivateKeyTagInput {
  final TCreatePrivateKeyTagBody body;

  TCreatePrivateKeyTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_private_key_tag`
typedef TCreatePrivateKeyTagBody = CreatePrivateKeyTagRequest;

/// `POST /public/v1/submit/create_private_keys`
typedef TCreatePrivateKeysResponse = ActivityResponse;

/// `POST /public/v1/submit/create_private_keys`
class TCreatePrivateKeysInput {
  final TCreatePrivateKeysBody body;

  TCreatePrivateKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_private_keys`
typedef TCreatePrivateKeysBody = CreatePrivateKeysRequest;

/// `POST /public/v1/submit/create_read_only_session`
typedef TCreateReadOnlySessionResponse = ActivityResponse;

/// `POST /public/v1/submit/create_read_only_session`
class TCreateReadOnlySessionInput {
  final TCreateReadOnlySessionBody body;

  TCreateReadOnlySessionInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_read_only_session`
typedef TCreateReadOnlySessionBody = CreateReadOnlySessionRequest;

/// `POST /public/v1/submit/create_read_write_session`
typedef TCreateReadWriteSessionResponse = ActivityResponse;

/// `POST /public/v1/submit/create_read_write_session`
class TCreateReadWriteSessionInput {
  final TCreateReadWriteSessionBody body;

  TCreateReadWriteSessionInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_read_write_session`
typedef TCreateReadWriteSessionBody = CreateReadWriteSessionRequest;

/// `POST /public/v1/submit/create_smart_contract_interface`
typedef TCreateSmartContractInterfaceResponse = ActivityResponse;

/// `POST /public/v1/submit/create_smart_contract_interface`
class TCreateSmartContractInterfaceInput {
  final TCreateSmartContractInterfaceBody body;

  TCreateSmartContractInterfaceInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_smart_contract_interface`
typedef TCreateSmartContractInterfaceBody = CreateSmartContractInterfaceRequest;

/// `POST /public/v1/submit/create_sub_organization`
typedef TCreateSubOrganizationResponse = ActivityResponse;

/// `POST /public/v1/submit/create_sub_organization`
class TCreateSubOrganizationInput {
  final TCreateSubOrganizationBody body;

  TCreateSubOrganizationInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_sub_organization`
typedef TCreateSubOrganizationBody = CreateSubOrganizationRequest;

/// `POST /public/v1/submit/create_user_tag`
typedef TCreateUserTagResponse = ActivityResponse;

/// `POST /public/v1/submit/create_user_tag`
class TCreateUserTagInput {
  final TCreateUserTagBody body;

  TCreateUserTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_user_tag`
typedef TCreateUserTagBody = CreateUserTagRequest;

/// `POST /public/v1/submit/create_users`
typedef TCreateUsersResponse = ActivityResponse;

/// `POST /public/v1/submit/create_users`
class TCreateUsersInput {
  final TCreateUsersBody body;

  TCreateUsersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_users`
typedef TCreateUsersBody = CreateUsersRequest;

/// `POST /public/v1/submit/create_wallet`
typedef TCreateWalletResponse = ActivityResponse;

/// `POST /public/v1/submit/create_wallet`
class TCreateWalletInput {
  final TCreateWalletBody body;

  TCreateWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_wallet`
typedef TCreateWalletBody = CreateWalletRequest;

/// `POST /public/v1/submit/create_wallet_accounts`
typedef TCreateWalletAccountsResponse = ActivityResponse;

/// `POST /public/v1/submit/create_wallet_accounts`
class TCreateWalletAccountsInput {
  final TCreateWalletAccountsBody body;

  TCreateWalletAccountsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/create_wallet_accounts`
typedef TCreateWalletAccountsBody = CreateWalletAccountsRequest;

/// `POST /public/v1/submit/delete_api_keys`
typedef TDeleteApiKeysResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_api_keys`
class TDeleteApiKeysInput {
  final TDeleteApiKeysBody body;

  TDeleteApiKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_api_keys`
typedef TDeleteApiKeysBody = DeleteApiKeysRequest;

/// `POST /public/v1/submit/delete_authenticators`
typedef TDeleteAuthenticatorsResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_authenticators`
class TDeleteAuthenticatorsInput {
  final TDeleteAuthenticatorsBody body;

  TDeleteAuthenticatorsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_authenticators`
typedef TDeleteAuthenticatorsBody = DeleteAuthenticatorsRequest;

/// `POST /public/v1/submit/delete_invitation`
typedef TDeleteInvitationResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_invitation`
class TDeleteInvitationInput {
  final TDeleteInvitationBody body;

  TDeleteInvitationInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_invitation`
typedef TDeleteInvitationBody = DeleteInvitationRequest;

/// `POST /public/v1/submit/delete_oauth_providers`
typedef TDeleteOauthProvidersResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_oauth_providers`
class TDeleteOauthProvidersInput {
  final TDeleteOauthProvidersBody body;

  TDeleteOauthProvidersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_oauth_providers`
typedef TDeleteOauthProvidersBody = DeleteOauthProvidersRequest;

/// `POST /public/v1/submit/delete_policy`
typedef TDeletePolicyResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_policy`
class TDeletePolicyInput {
  final TDeletePolicyBody body;

  TDeletePolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_policy`
typedef TDeletePolicyBody = DeletePolicyRequest;

/// `POST /public/v1/submit/delete_private_key_tags`
typedef TDeletePrivateKeyTagsResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_private_key_tags`
class TDeletePrivateKeyTagsInput {
  final TDeletePrivateKeyTagsBody body;

  TDeletePrivateKeyTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_private_key_tags`
typedef TDeletePrivateKeyTagsBody = DeletePrivateKeyTagsRequest;

/// `POST /public/v1/submit/delete_private_keys`
typedef TDeletePrivateKeysResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_private_keys`
class TDeletePrivateKeysInput {
  final TDeletePrivateKeysBody body;

  TDeletePrivateKeysInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_private_keys`
typedef TDeletePrivateKeysBody = DeletePrivateKeysRequest;

/// `POST /public/v1/submit/delete_smart_contract_interface`
typedef TDeleteSmartContractInterfaceResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_smart_contract_interface`
class TDeleteSmartContractInterfaceInput {
  final TDeleteSmartContractInterfaceBody body;

  TDeleteSmartContractInterfaceInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_smart_contract_interface`
typedef TDeleteSmartContractInterfaceBody = DeleteSmartContractInterfaceRequest;

/// `POST /public/v1/submit/delete_sub_organization`
typedef TDeleteSubOrganizationResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_sub_organization`
class TDeleteSubOrganizationInput {
  final TDeleteSubOrganizationBody body;

  TDeleteSubOrganizationInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_sub_organization`
typedef TDeleteSubOrganizationBody = DeleteSubOrganizationRequest;

/// `POST /public/v1/submit/delete_user_tags`
typedef TDeleteUserTagsResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_user_tags`
class TDeleteUserTagsInput {
  final TDeleteUserTagsBody body;

  TDeleteUserTagsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_user_tags`
typedef TDeleteUserTagsBody = DeleteUserTagsRequest;

/// `POST /public/v1/submit/delete_users`
typedef TDeleteUsersResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_users`
class TDeleteUsersInput {
  final TDeleteUsersBody body;

  TDeleteUsersInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_users`
typedef TDeleteUsersBody = DeleteUsersRequest;

/// `POST /public/v1/submit/delete_wallets`
typedef TDeleteWalletsResponse = ActivityResponse;

/// `POST /public/v1/submit/delete_wallets`
class TDeleteWalletsInput {
  final TDeleteWalletsBody body;

  TDeleteWalletsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/delete_wallets`
typedef TDeleteWalletsBody = DeleteWalletsRequest;

/// `POST /public/v1/submit/email_auth`
typedef TEmailAuthResponse = ActivityResponse;

/// `POST /public/v1/submit/email_auth`
class TEmailAuthInput {
  final TEmailAuthBody body;

  TEmailAuthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/email_auth`
typedef TEmailAuthBody = EmailAuthRequest;

/// `POST /public/v1/submit/export_private_key`
typedef TExportPrivateKeyResponse = ActivityResponse;

/// `POST /public/v1/submit/export_private_key`
class TExportPrivateKeyInput {
  final TExportPrivateKeyBody body;

  TExportPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/export_private_key`
typedef TExportPrivateKeyBody = ExportPrivateKeyRequest;

/// `POST /public/v1/submit/export_wallet`
typedef TExportWalletResponse = ActivityResponse;

/// `POST /public/v1/submit/export_wallet`
class TExportWalletInput {
  final TExportWalletBody body;

  TExportWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/export_wallet`
typedef TExportWalletBody = ExportWalletRequest;

/// `POST /public/v1/submit/export_wallet_account`
typedef TExportWalletAccountResponse = ActivityResponse;

/// `POST /public/v1/submit/export_wallet_account`
class TExportWalletAccountInput {
  final TExportWalletAccountBody body;

  TExportWalletAccountInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/export_wallet_account`
typedef TExportWalletAccountBody = ExportWalletAccountRequest;

/// `POST /public/v1/submit/import_private_key`
typedef TImportPrivateKeyResponse = ActivityResponse;

/// `POST /public/v1/submit/import_private_key`
class TImportPrivateKeyInput {
  final TImportPrivateKeyBody body;

  TImportPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/import_private_key`
typedef TImportPrivateKeyBody = ImportPrivateKeyRequest;

/// `POST /public/v1/submit/import_wallet`
typedef TImportWalletResponse = ActivityResponse;

/// `POST /public/v1/submit/import_wallet`
class TImportWalletInput {
  final TImportWalletBody body;

  TImportWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/import_wallet`
typedef TImportWalletBody = ImportWalletRequest;

/// `POST /public/v1/submit/init_fiat_on_ramp`
typedef TInitFiatOnRampResponse = ActivityResponse;

/// `POST /public/v1/submit/init_fiat_on_ramp`
class TInitFiatOnRampInput {
  final TInitFiatOnRampBody body;

  TInitFiatOnRampInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_fiat_on_ramp`
typedef TInitFiatOnRampBody = InitFiatOnRampRequest;

/// `POST /public/v1/submit/init_import_private_key`
typedef TInitImportPrivateKeyResponse = ActivityResponse;

/// `POST /public/v1/submit/init_import_private_key`
class TInitImportPrivateKeyInput {
  final TInitImportPrivateKeyBody body;

  TInitImportPrivateKeyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_import_private_key`
typedef TInitImportPrivateKeyBody = InitImportPrivateKeyRequest;

/// `POST /public/v1/submit/init_import_wallet`
typedef TInitImportWalletResponse = ActivityResponse;

/// `POST /public/v1/submit/init_import_wallet`
class TInitImportWalletInput {
  final TInitImportWalletBody body;

  TInitImportWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_import_wallet`
typedef TInitImportWalletBody = InitImportWalletRequest;

/// `POST /public/v1/submit/init_otp`
typedef TInitOtpResponse = ActivityResponse;

/// `POST /public/v1/submit/init_otp`
class TInitOtpInput {
  final TInitOtpBody body;

  TInitOtpInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_otp`
typedef TInitOtpBody = InitOtpRequest;

/// `POST /public/v1/submit/init_otp_auth`
typedef TInitOtpAuthResponse = ActivityResponse;

/// `POST /public/v1/submit/init_otp_auth`
class TInitOtpAuthInput {
  final TInitOtpAuthBody body;

  TInitOtpAuthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_otp_auth`
typedef TInitOtpAuthBody = InitOtpAuthRequest;

/// `POST /public/v1/submit/init_user_email_recovery`
typedef TInitUserEmailRecoveryResponse = ActivityResponse;

/// `POST /public/v1/submit/init_user_email_recovery`
class TInitUserEmailRecoveryInput {
  final TInitUserEmailRecoveryBody body;

  TInitUserEmailRecoveryInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/init_user_email_recovery`
typedef TInitUserEmailRecoveryBody = InitUserEmailRecoveryRequest;

/// `POST /public/v1/submit/oauth`
typedef TOauthResponse = ActivityResponse;

/// `POST /public/v1/submit/oauth`
class TOauthInput {
  final TOauthBody body;

  TOauthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/oauth`
typedef TOauthBody = OauthRequest;

/// `POST /public/v1/submit/oauth_login`
typedef TOauthLoginResponse = ActivityResponse;

/// `POST /public/v1/submit/oauth_login`
class TOauthLoginInput {
  final TOauthLoginBody body;

  TOauthLoginInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/oauth_login`
typedef TOauthLoginBody = OauthLoginRequest;

/// `POST /public/v1/submit/otp_auth`
typedef TOtpAuthResponse = ActivityResponse;

/// `POST /public/v1/submit/otp_auth`
class TOtpAuthInput {
  final TOtpAuthBody body;

  TOtpAuthInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/otp_auth`
typedef TOtpAuthBody = OtpAuthRequest;

/// `POST /public/v1/submit/otp_login`
typedef TOtpLoginResponse = ActivityResponse;

/// `POST /public/v1/submit/otp_login`
class TOtpLoginInput {
  final TOtpLoginBody body;

  TOtpLoginInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/otp_login`
typedef TOtpLoginBody = OtpLoginRequest;

/// `POST /public/v1/submit/recover_user`
typedef TRecoverUserResponse = ActivityResponse;

/// `POST /public/v1/submit/recover_user`
class TRecoverUserInput {
  final TRecoverUserBody body;

  TRecoverUserInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/recover_user`
typedef TRecoverUserBody = RecoverUserRequest;

/// `POST /public/v1/submit/reject_activity`
typedef TRejectActivityResponse = ActivityResponse;

/// `POST /public/v1/submit/reject_activity`
class TRejectActivityInput {
  final TRejectActivityBody body;

  TRejectActivityInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/reject_activity`
typedef TRejectActivityBody = RejectActivityRequest;

/// `POST /public/v1/submit/remove_organization_feature`
typedef TRemoveOrganizationFeatureResponse = ActivityResponse;

/// `POST /public/v1/submit/remove_organization_feature`
class TRemoveOrganizationFeatureInput {
  final TRemoveOrganizationFeatureBody body;

  TRemoveOrganizationFeatureInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/remove_organization_feature`
typedef TRemoveOrganizationFeatureBody = RemoveOrganizationFeatureRequest;

/// `POST /public/v1/submit/set_organization_feature`
typedef TSetOrganizationFeatureResponse = ActivityResponse;

/// `POST /public/v1/submit/set_organization_feature`
class TSetOrganizationFeatureInput {
  final TSetOrganizationFeatureBody body;

  TSetOrganizationFeatureInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/set_organization_feature`
typedef TSetOrganizationFeatureBody = SetOrganizationFeatureRequest;

/// `POST /public/v1/submit/sign_raw_payload`
typedef TSignRawPayloadResponse = ActivityResponse;

/// `POST /public/v1/submit/sign_raw_payload`
class TSignRawPayloadInput {
  final TSignRawPayloadBody body;

  TSignRawPayloadInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/sign_raw_payload`
typedef TSignRawPayloadBody = SignRawPayloadRequest;

/// `POST /public/v1/submit/sign_raw_payloads`
typedef TSignRawPayloadsResponse = ActivityResponse;

/// `POST /public/v1/submit/sign_raw_payloads`
class TSignRawPayloadsInput {
  final TSignRawPayloadsBody body;

  TSignRawPayloadsInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/sign_raw_payloads`
typedef TSignRawPayloadsBody = SignRawPayloadsRequest;

/// `POST /public/v1/submit/sign_transaction`
typedef TSignTransactionResponse = ActivityResponse;

/// `POST /public/v1/submit/sign_transaction`
class TSignTransactionInput {
  final TSignTransactionBody body;

  TSignTransactionInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/sign_transaction`
typedef TSignTransactionBody = SignTransactionRequest;

/// `POST /public/v1/submit/stamp_login`
typedef TStampLoginResponse = ActivityResponse;

/// `POST /public/v1/submit/stamp_login`
class TStampLoginInput {
  final TStampLoginBody body;

  TStampLoginInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/stamp_login`
typedef TStampLoginBody = StampLoginRequest;

/// `POST /public/v1/submit/update_policy`
typedef TUpdatePolicyResponse = ActivityResponse;

/// `POST /public/v1/submit/update_policy`
class TUpdatePolicyInput {
  final TUpdatePolicyBody body;

  TUpdatePolicyInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_policy`
typedef TUpdatePolicyBody = UpdatePolicyRequest;

/// `POST /public/v1/submit/update_private_key_tag`
typedef TUpdatePrivateKeyTagResponse = ActivityResponse;

/// `POST /public/v1/submit/update_private_key_tag`
class TUpdatePrivateKeyTagInput {
  final TUpdatePrivateKeyTagBody body;

  TUpdatePrivateKeyTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_private_key_tag`
typedef TUpdatePrivateKeyTagBody = UpdatePrivateKeyTagRequest;

/// `POST /public/v1/submit/update_root_quorum`
typedef TUpdateRootQuorumResponse = ActivityResponse;

/// `POST /public/v1/submit/update_root_quorum`
class TUpdateRootQuorumInput {
  final TUpdateRootQuorumBody body;

  TUpdateRootQuorumInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_root_quorum`
typedef TUpdateRootQuorumBody = UpdateRootQuorumRequest;

/// `POST /public/v1/submit/update_user`
typedef TUpdateUserResponse = ActivityResponse;

/// `POST /public/v1/submit/update_user`
class TUpdateUserInput {
  final TUpdateUserBody body;

  TUpdateUserInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_user`
typedef TUpdateUserBody = UpdateUserRequest;

/// `POST /public/v1/submit/update_user_email`
typedef TUpdateUserEmailResponse = ActivityResponse;

/// `POST /public/v1/submit/update_user_email`
class TUpdateUserEmailInput {
  final TUpdateUserEmailBody body;

  TUpdateUserEmailInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_user_email`
typedef TUpdateUserEmailBody = UpdateUserEmailRequest;

/// `POST /public/v1/submit/update_user_name`
typedef TUpdateUserNameResponse = ActivityResponse;

/// `POST /public/v1/submit/update_user_name`
class TUpdateUserNameInput {
  final TUpdateUserNameBody body;

  TUpdateUserNameInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_user_name`
typedef TUpdateUserNameBody = UpdateUserNameRequest;

/// `POST /public/v1/submit/update_user_phone_number`
typedef TUpdateUserPhoneNumberResponse = ActivityResponse;

/// `POST /public/v1/submit/update_user_phone_number`
class TUpdateUserPhoneNumberInput {
  final TUpdateUserPhoneNumberBody body;

  TUpdateUserPhoneNumberInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_user_phone_number`
typedef TUpdateUserPhoneNumberBody = UpdateUserPhoneNumberRequest;

/// `POST /public/v1/submit/update_user_tag`
typedef TUpdateUserTagResponse = ActivityResponse;

/// `POST /public/v1/submit/update_user_tag`
class TUpdateUserTagInput {
  final TUpdateUserTagBody body;

  TUpdateUserTagInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_user_tag`
typedef TUpdateUserTagBody = UpdateUserTagRequest;

/// `POST /public/v1/submit/update_wallet`
typedef TUpdateWalletResponse = ActivityResponse;

/// `POST /public/v1/submit/update_wallet`
class TUpdateWalletInput {
  final TUpdateWalletBody body;

  TUpdateWalletInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/update_wallet`
typedef TUpdateWalletBody = UpdateWalletRequest;

/// `POST /public/v1/submit/verify_otp`
typedef TVerifyOtpResponse = ActivityResponse;

/// `POST /public/v1/submit/verify_otp`
class TVerifyOtpInput {
  final TVerifyOtpBody body;

  TVerifyOtpInput({
    required this.body,
  });
}

/// `POST /public/v1/submit/verify_otp`
typedef TVerifyOtpBody = VerifyOtpRequest;
