name: turnkey_crypto
description: |
  This package consolidates some common cryptographic utilities used across our applications,
  particularly primitives related to keys, encryption, and decryption in a pure Dart implementation.
version: 0.1.2
repository: https://github.com/tkhq/dart-sdk

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  turnkey_encoding: ^0.1.0
  pointycastle: ^3.9.0
  base58check: ^2.0.0
  bs58: ^1.0.2
  cryptography: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
