import 'dart:io';
import 'package:path/path.dart' as path;

final String INPUT_SWAGGER_DIRECTORY = Directory('lib/swagger').absolute.path;
final String OUTPUT_GENERATED_DIRECTORY =  Directory('lib/__generated__').absolute.path;

final GENERATED_DIR = path.join(Directory.current.path, '../__generated__/');

const STAMP_HEADER_FIELD_KEY = "X-Stamp-WebAuthn";
const COMMENT_HEADER =
    "/* @generated by `turnkey_codegen`. DO NOT EDIT BY HAND */";

// namespace map

const Map<String, String> NAMESPACE_TO_DART_PREFIX = {
  "PublicApiService": "",
  "AuthProxyService": "Proxy",
};

const Map<String, (String, String, String)> VERSIONED_ACTIVITY_TYPES = {
  'ACTIVITY_TYPE_CREATE_AUTHENTICATORS':
      ('ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2', 'v1CreateAuthenticatorsIntentV2', 'v1CreateAuthenticatorsResult'),
  'ACTIVITY_TYPE_CREATE_API_KEYS': ('ACTIVITY_TYPE_CREATE_API_KEYS_V2', 'v1CreateApiKeysIntentV2', 'v1CreateApiKeysResult'),
  'ACTIVITY_TYPE_CREATE_POLICY': ('ACTIVITY_TYPE_CREATE_POLICY_V3', 'v1CreatePolicyIntentV3', 'v1CreatePolicyResult'),
  'ACTIVITY_TYPE_CREATE_PRIVATE_KEYS': ('ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2', 'v1CreatePrivateKeysIntentV2', 'v1CreatePrivateKeysResultV2'),
  'ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION':
      ('ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V7', 'v1CreateSubOrganizationIntentV7', 'v1CreateSubOrganizationResultV7'),
  'ACTIVITY_TYPE_CREATE_USERS': ('ACTIVITY_TYPE_CREATE_USERS_V3', 'v1CreateUsersIntentV3', 'v1CreateUsersResult'),
  'ACTIVITY_TYPE_SIGN_RAW_PAYLOAD': ('ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2', 'v1SignRawPayloadIntentV2', 'v1SignRawPayloadResult'),
  'ACTIVITY_TYPE_SIGN_TRANSACTION': ('ACTIVITY_TYPE_SIGN_TRANSACTION_V2', 'v1SignTransactionIntentV2', 'v1SignTransactionResult'),
  'ACTIVITY_TYPE_EMAIL_AUTH': ('ACTIVITY_TYPE_EMAIL_AUTH_V2', 'v1EmailAuthIntentV2', 'v1EmailAuthResult'),
  'ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION':
      ('ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION_V2', 'v1CreateReadWriteSessionIntentV2', 'v1CreateReadWriteSessionResult'),
  'ACTIVITY_TYPE_UPDATE_POLICY': ('ACTIVITY_TYPE_UPDATE_POLICY_V2', 'v1UpdatePolicyIntentV2', 'v1UpdatePolicyResultV2'),
  'ACTIVITY_TYPE_INIT_OTP_AUTH': ('ACTIVITY_TYPE_INIT_OTP_AUTH_V2', 'v1InitOtpAuthIntentV2', 'v1InitOtpAuthResultV2'),
  'ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY': ('ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY', 'v1InitUserEmailRecoveryIntent', 'v1InitUserEmailRecoveryResult'),
  'ACTIVITY_TYPE_INIT_OTP': ('ACTIVITY_TYPE_INIT_OTP', 'v1InitOtpIntent', 'v1InitOtpResult'),
};
