/* @generated by `turnkey_codegen`. DO NOT EDIT BY HAND */

import "models.dart";
import "../base.dart";
import "../version.dart";
import "dart:convert";
import "dart:async";
import "dart:io";

/// HTTP Client for interacting with Turnkey API
class TurnkeyClient {
  final THttpConfig config;
  final TStamper stamper;

  TurnkeyClient({required this.config, required this.stamper}) {
    if (config.baseUrl.isEmpty) {
      throw Exception('Missing base URL. Please verify environment variables.');
    }
  }

  Future<TResponseType> request<TBodyType, TResponseType>(
    String url,
    TBodyType body,
    TResponseType Function(Map<String, dynamic>) fromJson,
  ) async {
    final fullUrl = '${config.baseUrl}$url';
    final stringifiedBody = jsonEncode(body);
    final stamp = await stamper.stamp(stringifiedBody);

    final client = HttpClient();
    try {
      final request = await client.postUrl(Uri.parse(fullUrl));
      request.headers.set(stamp.stampHeaderName, stamp.stampHeaderValue);
      request.headers.set('X-Client-Version', VERSION);
      request.headers.contentType = ContentType.json;
      request.write(stringifiedBody);

      final response = await request.close();

      if (response.statusCode != 200) {
        final errorBody = await response.transform(utf8.decoder).join();
        throw TurnkeyRequestError(
          GrpcStatus.fromJson(jsonDecode(errorBody)),
        );
      }

      final responseBody = await response.transform(utf8.decoder).join();
      final decodedJson = jsonDecode(responseBody) as Map<String, dynamic>;

      return fromJson(decodedJson);
    } finally {
      client.close();
    }
  }

  Future<TResponseType> authProxyRequest<TBodyType, TResponseType>(
    String url,
    TBodyType body,
    TResponseType Function(Map<String, dynamic>) fromJson,
  ) async {
    if (config.authProxyConfigId == null || config.authProxyConfigId!.isEmpty) {
      throw Exception(
          'Missing Auth Proxy config ID. Please verify environment variables.');
    }
    final fullUrl = '${config.authProxyBaseUrl}$url';
    final stringifiedBody = jsonEncode(body);

    final client = HttpClient();
    try {
      final request = await client.postUrl(Uri.parse(fullUrl));
      request.headers.set("X-Auth-Proxy-Config-ID", config.authProxyConfigId!);
      request.headers.set('X-Client-Version', VERSION);
      request.headers.contentType = ContentType.json;
      request.write(stringifiedBody);

      final response = await request.close();

      if (response.statusCode != 200) {
        final errorBody = await response.transform(utf8.decoder).join();
        throw TurnkeyRequestError(
          GrpcStatus.fromJson(jsonDecode(errorBody)),
        );
      }

      final responseBody = await response.transform(utf8.decoder).join();
      final decodedJson = jsonDecode(responseBody) as Map<String, dynamic>;

      return fromJson(decodedJson);
    } finally {
      client.close();
    }
  }

  /// Build the server envelope.
  Map<String, dynamic> makeEnvelope({
    required String type,
    required String organizationId,
    required String timestampMs,
    required Map<String, dynamic> parameters,
  }) {
    return {
      'type': type,
      'organizationId': organizationId,
      'timestampMs': timestampMs,
      'parameters': parameters,
    };
  }

  /// Build `parameters` by taking everything from [src] except the keys in [exclude].
  /// Null values are dropped by default to keep payloads lean.
  Map<String, dynamic> paramsFromBody(
    Map<String, dynamic> src, {
    Iterable<String> exclude = const [],
    bool dropNulls = true,
  }) {
    final out = Map<String, dynamic>.from(src);
    for (final k in exclude) {
      out.remove(k);
    }
    // Optionally drop nulls
    if (dropNulls) {
      out.removeWhere((_, v) => v == null);
    }
    return out;
  }

  /// For command/activityDecision bodies generated by codegen:
  Map<String, dynamic> packActivityBody({
    required Map<String, dynamic> bodyJson,
    required String fallbackOrganizationId,
    required String activityType,
  }) {
    final orgId =
        (bodyJson['organizationId'] as String?) ?? fallbackOrganizationId;
    final ts = bodyJson['timestampMs'] as String? ??
        DateTime.now().millisecondsSinceEpoch.toString();

    // Exclude envelope keys (and guard against accidental nesting)
    final params = paramsFromBody(
      bodyJson,
      exclude: const ['organizationId', 'timestampMs'],
    );

    return makeEnvelope(
      type: activityType,
      organizationId: orgId,
      timestampMs: ts,
      parameters: params,
    );
  }

  /// Transforms activity response to flatten specific result from activity.result.{specificResult} to top-level result
  Map<String, dynamic> transformActivityResponse(
      Map<String, dynamic> json, String operationId) {
    // Convert operationId to the expected result field name (e.g., "StampLogin" -> "stampLoginResult")
    final resultFieldName =
        '${operationId[0].toLowerCase()}${operationId.substring(1)}Result';

    final result = <String, dynamic>{
      'activity': json['activity'],
    };

    // Extract specific result from activity.result.{specificResult} and flatten to top level
    if (json['activity'] != null &&
        json['activity']['result'] != null &&
        json['activity']['result'][resultFieldName] != null) {
      result['result'] = json['activity']['result'][resultFieldName];
    }

    return result;
  }
}
